spring.application.name=ordemservico
server.port=9898
server.servlet.context-path=/api
# Configuracoes de banco de dados - MariaDB
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/awos?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Estratégia de criação/atualização das tabelas
spring.jpa.hibernate.ddl-auto=none

# Mostrar SQL gerado (opcional, útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true